---
- name: Install and Configure Apache HTTP Server
  hosts: 192.168.1.21
  become: yes

  tasks:
    - name: Update yum cache
      yum:
        update_cache: yes

    - name: Install Apache HTTP Server
      yum:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Allow Apache through firewall
      ufw:
        rule: allow
        name: Apache
        port: http

    - name: Create index.html file
      copy:
        content: "<html><h1>Salma Salah Welcome You !</h1></html>"
        dest: /var/www/html/index.html
